blog/templatetags/urls.py
from django.template import Library

register = Library()


@register.simple_tag
def url_replace(request, field, value):
    dict_ = request.GET.copy()
    dict_[field] = value
    return dict_.urlencode()

blog/urls.py
from django.conf.urls import patterns, url
from blog import views

urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='index'),
    # url(r'^archive/$', views.archive, name='archive'),
    url(r'^search/$', views.SearchPostListView.as_view(), name='search'),
    url(r'^post/$', views.PostCreateView.as_view(), name='create'),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='edit'),
    url(r'^post/(?P<pk>\d+)/delete/$', views.PostDeleteView.as_view(), name='delete'),
    url(r'^tag/$', views.TagListView.as_view(), name='tags'),
    url(r'^tag/search/$', views.SearchTagListView.as_view(), name='tag-search'),
    url(r'^tag/(?P<slug>[-\w]+)/$', views.PostByTagListView.as_view(), name='tag'),
]

main/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.contrib import admin
admin.autodiscover()

import views

urlpatterns = [
    # Examples:
    url(r'^$', views.home, name='home'),
    url(r'^gsoc/$', views.gsoc, name='gsoc'),
    url(r'^scrobbler/$', views.scrobbler, name='scrobbler'),
    url(r'^schedule/$', views.schedule, name='schedule'),
    url(r'^about/$', views.about, name='about'),
    url(r'^about/travel/$', views.travel, name='travel'),
    url(r'^base/$', views.base, name='base'),
    url(r'^projects/$', views.projects, name='projects'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^fitness/', include('fitness.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    # url(r'^test/', RedirectView.as_view(url=reverse_lazy('joinme:index')), name='redirect-joinme'),
]

handler404 = views.handler404
handler403 = views.handler403
handler500 = views.handler500

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
import datetime
from django.utils import timezone
from taggit.managers import TaggableManager


class Post(models.Model):

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    title = models.CharField(max_length=200)
    intro = models.TextField()
    post = models.TextField(blank=True)
    pub_date = models.DateTimeField(auto_now_add=True, blank=True)
    tags = TaggableManager(blank=True)
    active = models.BooleanField(default=False)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

blog/forms.py
from django import forms

from blog.models import Post


class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'intro', 'post', 'tags', 'active')
        widgets = {
            'intro': forms.Textarea(attrs={'rows': 4})
        }

blog/views.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import render
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.http import Http404

import re

from blog.forms import *
from taggit.models import Tag


class SearchMixin(object):

    @staticmethod
    def normalize_query(query_string,
                        findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                        normspace=re.compile(r'\s{2,}').sub):
        return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)]

    def get_query(self, query_string, search_fields):
        # Query to search for every search term
        query = None
        terms = self.normalize_query(query_string)
        for term in terms:
            # Query to search for a given term in each field
            or_query = None
            for field_name in search_fields:
                q = Q(**{"%s__icontains" % field_name: term})
                if or_query is None:
                    or_query = q
                else:
                    or_query = or_query | q
            if query is None:
                query = or_query
            else:
                query = query | or_query
        return query


class LoginRequiredMixin(object):

    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view, login_url=reverse_lazy("blog:index"))


class NeverCacheMixin(object):

    @classmethod
    def as_view(cls, **initkwargs):
        view = super(NeverCacheMixin, cls).as_view(**initkwargs)
        return never_cache(view)


class PostListView(NeverCacheMixin, generic.ListView):
    model = Post
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        # context['page_title'] = 'Blog'
        return context


class PostDetailView(NeverCacheMixin, generic.DetailView):
    model = Post

    def get(self, request, *args, **kwargs):
        get = super(PostDetailView, self).get(request, *args, **kwargs)
        if not (request.user.is_staff or self.object.active):
            raise PermissionDenied
        return get

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_staff or self.object.active:
            context['page_title'] = self.get_object().title
        return context


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    form_class = PostCreateForm
    template_name_suffix = '_create_form'

    def get_context_data(self, **kwargs):
        context = super(PostCreateView, self).get_context_data(**kwargs)
        context['page_title'] = 'Create post'
        context['fa'] = 'plus-circle'
        return context


class PostUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Post
    form_class = PostCreateForm
    template_name_suffix = '_create_form'

    def get_context_data(self, **kwargs):
        context = super(PostUpdateView, self).get_context_data(**kwargs)
        context['page_title'] = 'Edit post'
        context['fa'] = 'edit'
        return context


class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

    def get_context_data(self, **kwargs):
        context = super(PostDeleteView, self).get_context_data(**kwargs)
        context['page_title'] = 'Delete post'
        context['fa'] = 'trash'
        return context


class SearchPostListView(SearchMixin, NeverCacheMixin, generic.ListView):
    model = Post
    template_name = 'blog/search_post.html'
    context_object_name = 'posts'

    def get_queryset(self):
        if ('q' in self.request.GET) and self.request.GET['q'].strip():
            query_string = self.request.GET['q'].strip()
            entry_query = self.get_query(
                query_string, ['title', 'intro', 'post'])
            return Post.objects.filter(entry_query).order_by('-pub_date')
        else:
            return Post.objects.all()

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            self.template_name = 'blog/search_post_ajax.html'
        return super(SearchPostListView, self).render_to_response(
            context, **response_kwargs)

    def get_context_data(self, **kwargs):
        context = super(SearchPostListView, self).get_context_data(**kwargs)
        if ('q' in self.request.GET) and self.request.GET['q'].strip():
            context['query'] = self.request.GET['q'].strip()
            context['page_title'] = self.request.GET['q'].strip()
        else:
            context['query'] = ''
            context['page_title'] = 'Search'
        context['fa'] = 'search'
        return context


class TagListView(NeverCacheMixin, generic.ListView):
    model = Tag
    template_name = 'blog/tag_list.html'
    context_object_name = 'tags'

    def get_context_data(self, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        context['page_title'] = 'Tags'
        context['fa'] = 'tags'
        return context


class PostByTagListView(NeverCacheMixin, generic.ListView):
    model = Post
    template_name = 'blog/tag_detail.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(PostByTagListView, self).get_context_data(**kwargs)
        try:
            tag = Tag.objects.get(slug=self.kwargs['slug'])
            context['page_title'] = tag.name
        except Tag.DoesNotExist:
            raise Http404
        context['fa'] = 'tag'
        return context


class SearchTagListView(SearchMixin, NeverCacheMixin, generic.ListView):
    model = Tag
    template_name = 'blog/search_tag_ajax.html'
    context_object_name = 'tags'

    def get_queryset(self):
        if ('q' in self.request.GET) and self.request.GET['q'].strip():
            query_string = self.request.GET['q'].strip()
            entry_query = self.get_query(query_string, ['name'])
            return Tag.objects.filter(entry_query)
        else:
            return Tag.objects.all()

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            self.template_name = 'blog/search_tag_ajax.html'
        return super(SearchTagListView, self).render_to_response(
            context, **response_kwargs)

    def get_context_data(self, **kwargs):
        context = super(SearchTagListView, self).get_context_data(**kwargs)
        if ('q' in self.request.GET) and self.request.GET['q'].strip():
            context['query'] = self.request.GET['q'].strip()
            context['page_title'] = self.request.GET['q'].strip()
        else:
            context['query'] = ''
            context['page_title'] = 'Search'
        context['fa'] = 'search'
        return context

blog/templates/blog/detail.html
{% extends "base.html" %}

{% load static %}

{% if user.is_authenticated %}
  {% block head_script %}
    <script src="{% static "js/tag.js" %}"></script>
  {% endblock head_script %}
{% endif %}

{% block page %}
  {% if post %}
    <article class="post detail" id="post_{{ post.id }}">
      <div>
      <p class="intro">{{ post.intro }}</p>
      {{ post.post|safe }}
      </div>
      {% if post.tags.all %}
      <p class="tags">
        <i class="fa fa-tags"></i>
        {# <code>[ #}
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:tag' tag.slug %}" class="btn btn-default btn-xs">{{ tag }}</a>
        {% endfor %}
        {# ]</code> #}
      </p>
      {% endif %}
      <p class="pub_date">
        {% if user.is_staff %}
        {% if not post.active %}
        <a href="{% url 'blog:edit' post.id %}" class="btn btn-xs btn-danger"><i class="fa fa-exclamation-triangle"></i></a>
        {% endif %}
        <a href="{% url 'blog:edit' post.id %}" class="btn btn-xs btn-default"><i class="fa fa-edit"></i></a>
        <a href="{% url 'blog:delete' post.id %}" class="btn btn-xs btn-default"><i class="fa fa-trash"></i></a>
        {% endif %}
        {{ post.pub_date|date:"F d, Y H:i" }}
      </p>
    </article>
    {# TODO:: prev and next #}
    {% comment %}
    <article class="prev_next">
      {% if prev %}
        <p class="left">
          <a href="{% url 'blog:detail' prev.id %}"> << {{ prev.title }}</a>
        </p>
      {% endif %}
      {% if next %}
        <p class="right">
          <a href="{% url 'blog:detail' next.id %}">{{ next.title }} >> </a>
        </p>
      {% endif %}
    </article>
    {% endcomment %}
  {% else %}
    <article class="warning">
      <h2>Warning</h2>
      <p class="intro">Nothing is found.</p>
    </article>
  {% endif %}
{% endblock page %}

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% load filters %}

{% block page %}
<div class="inner">
    {% if user.is_staff %}
    <form method="post" action="">
        {% csrf_token %}
        <div class="lead">Are you sure want to delete post &laquo;{{ object.title }}&raquo;?</div>
        <div class="btn-group" role="group">
            <button class="btn btn-danger">Delete <i class="fa fa-trash"></i></button>
            <a href="{% url 'blog:detail' object.pk %}" class="btn btn-default">Back</a>
        </div>
    </form>
    {% else %}
    <h2>403: forbidden...</h2>
    {% endif %}
</div>
{% endblock page %}

blog/templates/blog/post_create_form.html
{% extends "base.html" %}
{% load filters %}

{% block page %}
<div class="inner">
    {% if user.is_staff %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group {{ form.title.errors|yesno:"has-error," }}">
            <label for="{{ form.title.id_for_label }}" class="control-label">{{ form.title.label }}</label>
            {% if form.title.help_text %}
                <p class="help-block">{{ form.title.help_text }}</p>
            {% endif %}
            {{ form.title|add_class:"form-control" }}
            {% for error in form.title.errors %}
                <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="form-group {{ form.intro.errors|yesno:"has-error," }}">
            <label for="{{ form.intro.id_for_label }}" class="control-label">{{ form.intro.label }}</label>
            {% if form.intro.help_text %}
                <p class="help-block">{{ form.intro.help_text }}</p>
            {% endif %}
            {{ form.intro|add_class:"form-control" }}
            {% for error in form.intro.errors %}
                <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="form-group {{ form.post.errors|yesno:"has-error," }}">
            <label for="{{ form.post.id_for_label }}" class="control-label">{{ form.post.label }}</label>
            {% if form.post.help_text %}
                <p class="help-block">{{ form.post.help_text }}</p>
            {% endif %}
            {{ form.post|add_class:"form-control" }}
            {% for error in form.post.errors %}
                <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="form-group {{ form.tags.errors|yesno:"has-error," }}">
            <label for="{{ form.tags.id_for_label }}" class="control-label">{{ form.tags.label }}</label>
            {% if form.tags.help_text %}
                <p class="help-block">{{ form.tags.help_text }}</p>
            {% endif %}
            {{ form.tags|add_class:"form-control" }}
            {% for error in form.tags.errors %}
                <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="form-group {{ form.active.errors|yesno:"has-error," }}">
            <label for="{{ form.active.id_for_label }}" class="control-label">{{ form.active.label }} {{ form.active }}</label>
            {% if form.active.help_text %}
                <p class="help-block">{{ form.active.help_text }}</p>
            {% endif %}
            {% for error in form.active.errors %}
                <p class="help-block">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="hidden">
            <input type="hidden" id="search_tag_address" value="{% url 'blog:tag-search' %}">
        </div>
        <div class="btn-group" role="group">
            <button class="btn btn-success">Save <i class="fa fa-save"></i></button>
            {% if object %}
                <a href="{% url 'blog:detail' object.pk %}" class="btn btn-default">Back</a>
                <a href="{% url 'blog:delete' object.pk %}" class="btn btn-default"><i class="fa fa-trash"></i></a>
            {% endif %}
        </div>
    </form>
    {% else %}
    <h2>403: forbidden...</h2>
    {% endif %}
</div>
<script>
    CKEDITOR.replace( 'id_post' );

    /*$(window).on('beforeunload', function () {
        return 'Are you sure you want to leave this page?  You will lose any unsaved data.';
    });*/
</script>
{% endblock page %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% load static %}

{% if user.is_authenticated %}
    {% block head_script %}
        <script src="{% static "js/tag.js" %}"></script>
    {% endblock head_script %}
{% endif %}

{% block page %}
{% if post %}
    {% if user.is_staff or post.active %}
    <article class="post detail" id="post_{{ post.id }}">
        <div>
            <p class="intro">{{ post.intro }}</p>
            {{ post.post|safe }}
        </div>
        {% if post.tags.all %}
        <p class="tags">
            <i class="fa fa-tags"></i>
            {# <code>[ #}
            {% for tag in post.tags.all %}
            <a href="{% url 'blog:tag' tag.slug %}" class="btn btn-default btn-xs">{{ tag }}</a>
            {% endfor %}
            {# ]</code> #}
        </p>
        {% endif %}
        <p class="pub_date">
            {% if user.is_staff %}
            {% if not post.active %}
            <a href="{% url 'blog:edit' post.id %}" class="btn btn-xs btn-danger"><i class="fa fa-exclamation-triangle"></i></a>
            {% endif %}
            <a href="{% url 'blog:edit' post.id %}" class="btn btn-xs btn-default"><i class="fa fa-edit"></i></a>
            <a href="{% url 'blog:delete' post.id %}" class="btn btn-xs btn-default"><i class="fa fa-trash"></i></a>
            {% endif %}
            {{ post.pub_date|date:"F d, Y H:i" }}
        </p>
    </article>
    {% else %}
    <article class="warning">
        <h2>Warning</h2>
        <p class="intro">Access denied.</p>
    </article>
    {% endif %}
{% else %}
    <article class="warning">
        <h2>Warning</h2>
        <p class="intro">Nothing is found.</p>
    </article>
{% endif %}
{% endblock page %}

blog/templates/blog/post_iterator.html
<ul class="list-unstyled post-list">
{% for post in posts %}
    {% if user.is_staff or post.active %}
    <li class="post-item">
        <span class="pull-right post-item-pubdate">{{ post.pub_date|date:"F d, Y" }}</span>
        {% if user.is_staff and not post.active %}
            <i class="fa fa-exclamation-triangle"></i>
        {% endif %}
        <a href="{% url 'blog:detail' post.id %}" class="post-item-title">{{ post.title }}</a>
    </li>
    {% endif %}
{% endfor %}
</ul>

blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block page %}

{% regroup posts|dictsortreversed:"pub_date" by pub_date.year as by_year %}

{% for year in by_year %}
<article class="archive" data-year="{{ year.grouper }}">
    <h2>{{ year.grouper }}</h2>
    {% include "blog/post_iterator.html" with posts=year.list %}
</article>
{% empty %}
<article class="warning">
    <h2>Warning</h2>
    <p class="intro">Nothing is found.</p>
</article>
{% endfor %}

{% endblock page %}

blog/templates/blog/search_post.html
{% extends "base.html" %}
{% load urls %}

{% block page %}
    {% if posts %}
    <article>
        {% include "blog/post_iterator.html" with posts=posts %}
    </article>
    {% else %}
    <article class="warning">
        <h2>Warning</h2>
        <p class="intro">Nothing is found.</p>
    </article>
    {% endif %}
{% endblock page %}

blog/templates/blog/search_post_ajax.html
{% if posts %}
    <h2>Results</h2>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            {% include "blog/post_iterator.html" with posts=posts|slice:":5" %}
        </div>
    </div>
{% else %}
    <article class="warning">
        <h2>Warning</h2>
        <p class="intro">Nothing is found.</p>
    </article>
{% endif %}

blog/templates/blog/search_tag_ajax.html
{% for tag in tags %}
    <button type="button" class="btn btn-default search-tag-item" data-slug="{{ tag.slug }}">
        <span class="tag-name">{{ tag.name }}</span>
        <span class="tag-count badge">{{ tag.taggit_taggeditem_items.all.count }}</span>
    </button>
{% endfor %}

blog/templates/blog/tag_detail.html
{% extends "base.html" %}

{% block page %}
    {% if posts %}
    <article class="archive tag-detail">
        {% include "blog/post_iterator.html" with posts=posts %}
    </article>
    {% else %}
    <article class="warning">
        <h2>Warning</h2>
        <p class="intro">Nothing is found.</p>
    </article>
    {% endif %}
{% endblock page %}

blog/templates/blog/tag_list.html
{% extends "base.html" %}

{% block page %}
<article class="tag-list">
    {% if tags %}
        <hr>
        {% for tag in tags %}
            <a class="btn btn-default tag-item" href="{% url 'blog:tag' tag.slug %}">
                {{ tag.name }}
                {# <span class="badge">{{ tag.taggit_taggeditem_items.all.count }}</span> #}
            </a>
        {% endfor %}
        <hr>
    {% else %}
        <h2>Warning</h2>
        <p class="intro">Nothing is found.</p>
    {% endif %}
</article>
{% endblock page %}

blog/templates/blog/tags.html
{% extends "base.html" %}

{% block page %}
  <article class="tag-list">
  {% if tags %}
    <hr>
    {% for tag in tags %}
      <a class="btn btn-default tag-item" href="{% url 'blog:tag' tag.slug %}">
        {{ tag.name }} <span class="badge">{{ tag.taggit_taggeditem_items.all.count }}</span>
      </a>
    {% endfor %}
    <hr>
  {% else %}
      <h2>Warning</h2>
      <p class="intro">Nothing is found.</p>
  {% endif %}
  </article>
{% endblock page %}