blog/urls.py
from django.conf.urls import patterns, url
from blog import views

urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='index'),
    # url(r'^archive/$', views.archive, name='archive'),
    url(r'^search/$', views.SearchPostListView.as_view(), name='search'),
    url(r'^post/$', views.PostCreateView.as_view(), name='create'),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='edit'),
    url(r'^post/(?P<pk>\d+)/delete/$', views.PostDeleteView.as_view(), name='delete'),
    url(r'^tag/$', views.TagListView.as_view(), name='tags'),
    url(r'^tag/search/$', views.SearchTagListView.as_view(), name='tag-search'),
    url(r'^tag/(?P<slug>[-\w]+)/$', views.PostByTagListView.as_view(), name='tag'),
]

main/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.contrib import admin
admin.autodiscover()

import views

urlpatterns = [
    # Examples:
    url(r'^$', views.home, name='home'),
    url(r'^gsoc/$', views.gsoc, name='gsoc'),
    url(r'^scrobbler/$', views.scrobbler, name='scrobbler'),
    url(r'^schedule/$', views.schedule, name='schedule'),
    url(r'^about/$', views.about, name='about'),
    url(r'^about/travel/$', views.travel, name='travel'),
    url(r'^base/$', views.base, name='base'),
    url(r'^projects/$', views.projects, name='projects'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^fitness/', include('fitness.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    # url(r'^test/', RedirectView.as_view(url=reverse_lazy('joinme:index')), name='redirect-joinme'),
]

handler404 = views.handler404
handler403 = views.handler403
handler500 = views.handler500

menu/models.py
from django.db import models


class Menu(models.Model):

    class Meta:
        verbose_name = 'Menu'
        verbose_name_plural = 'Menus'
        ordering = ['sort']

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

    def has_subitems(self):
        return self.subitems.count() > 0

    TARGET_CHOICES = (
        ('EM', ''),
        ('BL', '_blank'),
        ('SF', '_self'),
        ('PR', '_parent'),
        ('TP', '_top'),
    )

    name = models.CharField(max_length=20)
    link = models.CharField(max_length=255)
    target = models.CharField(max_length=2, choices=TARGET_CHOICES, default='EM')
    sort = models.PositiveIntegerField(default=100)
    level = models.IntegerField(default=0)
    subitems = models.ManyToManyField('self', blank=True)
    for_staff = models.BooleanField(default=False)

    def is_active(self):
        return self.sort > 0
    is_active.admin_order_field = 'sort'
    is_active.boolean = True
    is_active.short_description = 'Is active?'

menu/templates/menu/menu.html
<button class="menu-toggle btn btn-default"
        data-toggle="collapse"
        data-target="#mainmenu"
        area-expanded="true"
        area-controls="mainmenu">
    <i class="fa fa-bars"></i>
</button>
<div class="collapse" id="mainmenu">
    <ul class="menu">
    {% for el in menu %}
        {% if not el.for_staff or el.for_staff and user.is_staff %}
            <li {% if el.has_subitems %} data-submenu="yes" {% endif %}>
                <a href="{{ el.link }}"
                   {% if el.get_target_display %}
                   target="{{ el.get_target_display }}"
                   {% endif %}>{{ el.name }}</a>
                {% if el.has_subitems %}
                    <ul class="submenu">
                    {% for subel in el.subitems.all %}
                        {% if not subel.for_staff or subel.for_staff and user.is_staff %}
                            <li>
                                <a href="{{ subel.link }}"
                                   {% if el.get_target_display %}
                                   target="{{ subel.get_target_display }}"
                                   {% endif %}>{{ subel.name }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                {% endif %} {# end of submenu #}
            </li>
      {% endif %}
    {% endfor %}
    </ul>
</div>