blog/urls.py
from django.conf.urls import patterns, url
from blog import views

urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='index'),
    # url(r'^archive/$', views.archive, name='archive'),
    url(r'^search/$', views.SearchPostListView.as_view(), name='search'),
    url(r'^post/$', views.PostCreateView.as_view(), name='create'),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='edit'),
    url(r'^post/(?P<pk>\d+)/delete/$', views.PostDeleteView.as_view(), name='delete'),
    url(r'^tag/$', views.TagListView.as_view(), name='tags'),
    url(r'^tag/search/$', views.SearchTagListView.as_view(), name='tag-search'),
    url(r'^tag/(?P<slug>[-\w]+)/$', views.PostByTagListView.as_view(), name='tag'),
]

main/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.contrib import admin
admin.autodiscover()

import views

urlpatterns = [
    # Examples:
    url(r'^$', views.home, name='home'),
    url(r'^gsoc/$', views.gsoc, name='gsoc'),
    url(r'^scrobbler/$', views.scrobbler, name='scrobbler'),
    url(r'^schedule/$', views.schedule, name='schedule'),
    url(r'^about/$', views.about, name='about'),
    url(r'^about/travel/$', views.travel, name='travel'),
    url(r'^base/$', views.base, name='base'),
    url(r'^projects/$', views.projects, name='projects'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^fitness/', include('fitness.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    # url(r'^test/', RedirectView.as_view(url=reverse_lazy('joinme:index')), name='redirect-joinme'),
]

handler404 = views.handler404
handler403 = views.handler403
handler500 = views.handler500

main/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from datetime import datetime


def home(request):
    obj = {
        'page_title': 'Igor Stepanov',
    }
    return render(request, 'vcard_sigorilla.html', obj)


def gsoc(request):
    obj = {
        'fa': 'code',
        'page_title': 'Google Summer of Code 2015',
    }
    return render(request, 'gsoc15.html', obj)


def about(request):
    obj = {
        'fa': 'user',
        'page_title': 'About me',
    }
    return render(request, 'about.html', obj)


def travel(request):
    obj = {
        'fa': 'globe',
        'page_title': 'Travel',
    }
    return render(request, 'travel.html', obj)


def scrobbler(request):
    obj = {
        'fa': 'lastfm-square',
        'page_title': 'Scrobbler',
    }
    return render(request, 'scrobbler.html', obj)


def schedule(request):
    curr_week = (datetime.now().isocalendar()[1] - 1) % 2 == 0
    obj = {
        'curr_week': curr_week,
        'fa': 'table',
        'page_title': 'Schedule',
    }
    return render(request, 'schedule.html', obj)


def base(request):
    return render(request, 'base.html')


def projects(request):
    obj = {
        'fa': 'code',
        'page_title': 'Projects',
    }
    return render(request, 'projects.html', obj)


def handler403(request):
    obj = {
        'fa': 'exclamation-circle',
        'page_title': '403: Forbidden',
    }
    return render(request, '403.html', obj)


def handler404(request):
    obj = {
        'fa': 'exclamation-circle',
        'page_title': '404: Not Found',
    }
    return render(request, '404.html', obj)


def handler500(request):
    obj = {
        'fa': 'exclamation-triangle',
        'page_title': '500: Internal Server Error',
    }
    return render(request, '500.html', obj)

main/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block page %}

<article class="index text-justify">
    <img src="{% static "images/igor.jpg" %}" alt="Igor" align="right" width="200" class="img-circle">
    <p>My name is Igor. I'm programmer from Moscow. Also I'm studying at <a href="//phystech.edu" target="_blank">MIPT</a></p>
    <p>I started programming in school at age of 14. I took part in different competitions betweet schools. I got interested in PHP and webdesign at 16. Since then I have been improving my abilities. C/C++, PHP, Javascript, HTML, CSS, Django, Python, MYSQL are all on the list of skills. I love frontend as well as backend development.</p>
    <p>I love hackathons. This summer I took part in Tizen Hackathon&nbsp;(Mobile operating system based on HTML5 and Javascript <a href="https://www.tizen.org" target="_blank">tizen.org</a>). My last homeproject is <a href="https://github.com/sigorilla/findme" target="_blank">FindMe</a>. I and my friends made <a href="/findme/">a GEO location social app</a> on Facebook Hackathon at MIPT.</p>
    <p>Other my projects you can see on <a href="https://github.com/sigorilla" target="_blank">my GitHub page</a>. All my contacts are on page <a href="/about/">About</a>.</p>
    <hr>
    <p>I want to visit all countries. So you can see my progress on <a href="{% url 'travel' %}">Travel page</a>.</p>
</article>

{% endblock page %}

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" prefix="og: http://ogp.me/ns#">
{% block head %}
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ page_title|default:"Homepage" }} | Igor Stepanov{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <meta name="title" content="{{ page_title|default:"Igor Stepanov" }}">
    <meta name="author" content="Igor Stepanov">
    <meta name="description" content="Homepage of Igor Stepanov">
    <meta property="og:title" content="{{ page_title|default:"Igor Stepanov" }}">
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{ current_uri }}">
    {# <meta property="og:image" content="http://{{ current_host }}{% static "images/title.png" %}"> #}
    <link rel="icon" type="image/x-icon" href="{% static "images/favicon.png" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "css/base.css" %}?v=0.2.2">
    <script src="//cdn.ckeditor.com/4.5.1/standard/ckeditor.js"></script>
    <script src="{% static "js/jquery-2.1.1.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/base.js" %}?v=0.1.2"></script>
    {% block end_script %} {% endblock end_script %}
    {% block head_script %}{% endblock head_script %}
  </head>
{% endblock head %}
<body>

{% block search %}
<div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModalLabel">
  <div class="modal-dialog modal-lg modal-search" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <form action="{% url 'blog:search' %}">
          <div class="input-group">
            <input id="search" type="text" name="q" class="input-search" placeholder="Search..." autocomplete="off">
            <span class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="fa fa-search"></i>
              </button>
              <button class="btn btn-default" data-dismiss="modal" aria-label="Close">
                <i class="fa fa-remove"></i>
              </button>
            </span>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock search %}

<nav>
  <div class="inner">
    <div class="text-right">
      <span class="pull-left"><strong><a href="/">Homepage</a></strong></span>
      {% block navigation %}
         {% load menu_top %}
         {% show_menu %}
{#        {% include "nav.html" %}#}
      {% endblock navigation %}
    </div>
  </div>
</nav>

{% block header %}
{% if page_title %}
<header id="header">
  <div class="inner">
    <h1>{% block page_title %} <i class="fa fa-{{ fa|default:'coffee' }}"></i> {{ page_title|default:"Igor Stepanov" }} {% endblock page_title %}</h1>
  </div>
</header>
{% endif %}
{% endblock header %}


<div id="main">
  {% block page %}
    <article class="base post detail">
      <p class="intro">This page shows all the elements implemented. List of contents is automatically created directly in the browser, so do not disable JavaScript. The same way <code>&lt;h5&gt;</code> and <code>&lt;h6&gt;</code> will be converted to <code>&lt;h4&gt;</code>, and <code>&lt;h1&gt;</code> to <code>&lt;h2&gt;</code>.</p>

      <h2>Second level</h2>
      <h3>Third</h3>
      <h4>Fourth</h4>
      <p>Now: {% now "H:i" %}</p>
      <p>Link: <a href="#1">ipsum</a>. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae iure quo asperiores obcaecati ducimus corrupti debitis atque, possimus autem alias!</p>
      <h3>Paragraph</h3>
      <h5>Fifth?</h5>
      <p>Abbreviation: <abbr title="Moscow Institute of Physics and Technology">MIPT</abbr>. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi, voluptatibus.</p>
      <h2>Some other info</h2>
      <h3>Table</h3>
      <table class="table table-bordered">
        <caption class="text-center">Table</caption>
        <tr>
          <td>1</td>
          <td>2</td>
          <td>3</td>
        </tr>
        <tr>
          <td>4</td>
          <td>5</td>
          <td>6</td>
        </tr>
      </table>
      <h3>Image</h3>
      <p>
        <img src="//pp.vk.me/c540104/c540100/v540100129/4de02/LjDm2XmoD-Q.jpg" alt="Nature">
        <label for="img">Title of picture</label>
      </p>
      {% if user.is_authenticated %}
      <h2>I'M ADMIN!!!</h2>
      {% endif %}
      <h3>Quote</h3>
      <blockquote>
        <p>Hello, world! This is quote.</p>
        <footer>Author in <cite>Magazine</cite></footer>
      </blockquote>
      <hr>
      <ol>
        <li>Lorem ipsum dolor.</li>
        <ol>
          <li>Lorem ipsum dolor sit.</li>
          <li>Lorem</li>
        </ol>
        <li>Lorem ipsum dolor sit.</li>
        <li>Lorem ipsum.</li>
      </ol>
      <h2>Conclusion</h2>
      <h3>Code</h3>
      <pre>// This block code...<br>var a = 1;</pre>
      <p>Some piece of code: <code>var b = {key: value};</code> This is example of inline code. Для написания html вставок используйте <code><</code> -- <span>&</span><span>lt;</span> и <code>></code> -- <span>&</span><span>gt;</span></p>
      <h3>Contact</h3>
      <p>Thank you for your attention! You can write me by:</p>
      <ul>
        <li><a href="//twitter.com/sigorillo">@sigorilla</a></li>
        <li>Other ways..</li>
      </ul>
      <p class="pub_date">Aug. 18, 2014, 12:50 p.m.</p>
    </article>
  {% endblock page %}
</div>

<footer id="footer">
  <div class="inner">
  {% block footer %}
    <div>
      <div class="btn-group btn-group-sm pull-right">
        <button class="btn btn-default" data-fire="totop" title="Go to Top">
          <i class="fa fa-arrow-up"></i>
        </button>
        <button class="btn btn-default" data-toggle="modal" data-target="#searchModal" title="Search">
          <i class="fa fa-search"></i>
        </button>
        <button class="btn btn-default" data-fire="print" title="Print this page">
          <i class="fa fa-print"></i>
        </button>
      </div>
      Igor Stepanov = <code>[
      <a href="//vk.com/sigorilla" target="_blank">vk</a>,
      <a href="//twitter.com/sigorillo" target="_blank">twitter</a>,
      <a href="//www.facebook.com/sigorilla" target="_blank">facebook</a>,
      <a href="mailto:sigorilla@gmail.com" target="_blank">email</a>,
    ]</code> &copy; 2012&ndash;{% now "Y" %}</div>
  {% endblock footer %}
  </div>
</footer>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter28303306 = new Ya.Metrika({id:28303306,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/28303306" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<!-- Google.Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53972648-3', 'auto');
  ga('send', 'pageview');
</script>
<!-- /Google.Analytics -->


</body>
</html>

main/templates/gsoc15.html
{% extends "base.html" %}

{% block page %}
<article class="gsoc post detail">
  <p class="intro">My proposal for <a href="//jquery.org" target="_blank">jQuery Foundation</a> on <a href="//www.google-melange.com/gsoc/homepage/google/gsoc2015" target="_blank">GSoC'15</a></p>

  <h2 id="info">Personal Information</h2>
  <h3 id="contact">Contacts</h3>
  <ul>
  <li><strong>Name:</strong> Igor Stepanov</li>
  <li><strong>University:</strong>&nbsp;<a href="http://phystech.edu/" target="_blank">Moscow Institute of Physics and Technology (State University)</a></li>
  <li><strong>Field of study:</strong> Applied Physics and Mathematics</li>
  <li><strong>Begin of studies:</strong> 2012</li>
  <li><strong>Expected graduation date:</strong> 2016</li>
  <li><strong>Degree:</strong> Bachelor of Science</li>
  <li><strong>Homepage:</strong> <a href="http://master-igor.com" target="_blank">master-igor.com</a></li>
  <li><strong>Email:</strong> <a href="mailto:sigorilla@gmail.com" target="_blank">sigorilla@gmail.com</a> or <a href="mailto:igor.stepanov@phystech.edu" target="_blank">igor.stepanov@phystech.edu</a></li>
  <li><strong>Tel:</strong> +7 (968) 471-89-55</li>
  <li><strong>IRC:</strong> sigorilla (on freenode)</li>
  <li><strong>Location:</strong> Russian Federation, Moscow</li>
  <li><strong>Timezone:</strong> UTC+3:00</li>
  <li><strong>Language:</strong> English (preference for communication), Russian</li>
  <li><strong>GitHub:</strong> <a href="http://github.com/sigorilla" target="_blank">sigorilla</a></li>
  <li><strong>Twitter:</strong> <a href="http://twitter.com/sigorillo" target="_blank">@sigorillo</a></li>
  <li><strong>Facebook:</strong> <a href="http://facebook.com/sigorilla" target="_blank">sigorilla</a></li>
  <li><strong>Skype:</strong> newuses-iga</li>
  </ul>
  <h3 id="skills">Coding skills</h3>
  <p>I started programming on Pascal in school at age of 14. I took part in different competitions betweet schools. I got interested in PHP and webdesign at 16. Since then I have been improving my abilities. C/C++, PHP, Javascript, HTML, CSS, Django, Python, MYSQL are all on the list of skills. I love frontend as well as backend development.</p>
  <p>I'm also fond of jQuery. I find it very convenient to develop web. I use it almost in every my project. By the way, I love hackathons. This summer I took part in Tizen Hackathon&nbsp;(Mobile operating system based on HTML5 and Javascript <a href="https://www.tizen.org" target="_blank">tizen.org</a>).</p>
  <p>My last homeproject is <a href="//master-igor.com" target="_blank">master-igor.com</a>. Two weeks ago I and my friends made a GEO location social app (<a href="http://master-igor.com/findme" target="_blank">master-igor.com/findme</a>)&nbsp;on Facebook Hackathon at MIPT.</p>
  <p>About year ago I started to work for <a href="//wanttoknow.ru/">wanttoknow.ru</a>&nbsp;(site for startup student company teaching schoolers basic subjects to pass state exams to enter the best universities of Russian Federation). I'm sort of CTO there. I'm administrating and supporting the whole site, dealing with technical problems.</p>

  <h2 id="project">Project Proposal</h2>
  <h3 id="pr-title">Title</h3>
  <p><strong>Interactive Tutorials for jQuery Learning Center</strong></p>
  <h3 id="pr-desc">Description</h3>
  <p>This project will be a repository on <a href="https://github.com">GitHub</a>, for which you can create folders with different levels of difficulty. Each folder will include the tasks as HTML pages with video (from YouTube) and various training slides such as cards or short questions. You must correctly answer tasks for further reading the article. Also you will be able to take a hint or get a full answer.</p>
  <p>The user will be required to write a necessary part of the existing code to subccessfully complete the task.</p>
  <p>Some tasks (steps) can be grouped into a chain, so user will have to solve all the steps to complete this task.</p>
  <p>More details how to get started you can see here: <a href="https://github.com/arschmitz/jquery-tutorials">arschmitz/jquery-tutorials</a>.</p>
  <h3 id="pr-time">Timeline</h3>

  <ul>
  <li><strong>27 April - 17 May (3 weeks)</strong>
  <ul>
  <li>Formalization of the idea with community (mentors).</li>
  <li>Reading documentation of Learning Center.</li>
  <li>Composing a list which contains the questions I need to ask my mentors.</li>
  </ul>
  </li>
  <li><strong>18 April - 24 May (1 weeks)</strong>
  <ul>
  <li>Getting in touch with mentors.</li>
  <li>Asking them questions from the list I made up during previous period.</li>
  <li>After discussions in IRC (by email, Skype, etc.) I will get the right idea about the project so I'll be able to work and go the right way solving project's problems and issues.</li>
  </ul>
  </li>
  <li><strong>25 May - 7 June (2 weeks)</strong>
  <ul>
  <li>Coding the backend of the project using qUnit.</li>
  <li>Creating some tasks to test code.</li>
  </ul>
  </li>
  <li><strong>8 June - 21 June (2 weeks)</strong>
  <ul>
  <li>Coding client-side of the project.</li>
  <li>Writing a verification system of tasks.</li>
  </ul>
  </li>
  <li><strong>22 June - 28 June (1 weeks)</strong>
  <ul>
  <li>Testing existing code before mid-term evaluations.</li>
  <li>Discussing with mentor about the existing work before I'll submit mid-term deadline.</li>
  </ul>
  </li>
  <li><strong>29 June - 5 July (1 week)</strong>
  <ul>
  <li>One week for a rest.</li>
  </ul>
  </li>
  <li><strong>6 July - 26 Jule (3 weeks)</strong>
  <ul>
  <li>Creating tasks, which will be able to embed on the pages.</li>
  <li>Adding slides, videos and some interesting information for users.</li>
  <li>Creating a simple and user-friendly interface for users.</li>
  </ul>
  </li>
  <li><strong>27 July - 9 August (2 weeks)</strong>
  <ul>
  <li>Making further changes in the code to improve application performance.</li>
  <li>Writing documentation of the project.</li>
  </ul>
  </li>
  <li><strong>10 July - 16 August (1 week)</strong>
  <ul>
  <li>Final testing and debugging.</li>
  <li>Editing documentation.</li>
  </ul>
  </li>
  <li><strong>17 July - 24 August (1 week)</strong>
  <ul>
  <li>Replacement week.</li>
  </ul>
  </li>
  <li><strong>before 25 September</strong>
  <ul>
  <li>"Soft" deadline for code sample submission.</li>
  </ul>
  </li>
  </ul>
  <h3 id="pr-tech">Technical Details</h3>
  <p>The base of pages will be completed with HTML and will be contained necessary scripts for testing.</p>
  <p>To run test and evaluate your solution just the user should click the blue "Run Tests" button in the upper right of the page. We'll use <a href="//qunitjs.com/" target="_blank">qUnit project</a> to check tasks. And we can add a tooltips to get the hint.</p>
  <h2 id="conclusion">Conclusion</h2>
  <p>I'm looking forward to coding in your project. I have so far opened three pull requests to your Github (<a href="//github.com/jquery/learn.jquery.com/pull/636" target="_blank">PR #636</a>, <a href="//github.com/jquery/jquery-wp-content/pull/344" target="_blank">PR #344</a> and <a href="//github.com/jquery/jquery-wp-content/pull/345" target="_blank">PR #345</a>), which I hope were useful. I have a right set of skills and huge motivation in my opinion. I think it will be a great opportunity for me to improve my knowledge of web development and get wonderful lifetime experience. It would nice to contribute to your project and become a member of community. Perphaps my work will be useful for you and your project.</p>
  <p>P.S. I would like to thank <a href="https://github.com/agcolom" target="_blank">Anne-Gaelle Colom</a> and <a href="https://github.com/arschmitz" target="_blank">Alexander Schmitz</a> for their feedback in creating this proposal.</p>
</article>
{% endblock page %}

main/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block page %}

<article class="index text-justify">
    <div class="jumbotron">
        <h2>Igor Stepanov homepage.</h2>
        <h3>Info coming soon...</h3>
    </div>
</article>

{% endblock page %}

main/templates/nav.html
<button class="menu-toggle btn btn-default" data-toggle="collapse" data-target="#mainmenu" area-expanded="true" area-controls="mainmenu"><i class="fa fa-bars"></i></button>
<div class="collapse" id="mainmenu">
<ul class="menu">
  {% if user.is_staff %}
    <li><a href="{% url 'blog:create' %}">New</a></li>
  {% endif %}
  <li><a href="{% url 'blog:index' %}">Blog</a></li>
  <li><a href="{% url 'about' %}">About</a></li>
  {# <li><a href="{% url 'schedule' %}">Schedule</a></li> #}
  <li><a href="{% url 'scrobbler' %}">Scrobbler</a></li>
  <li><a href="{% url 'admin:index' %}" target="_blank">Admin</a></li>
</ul></div>

main/templates/projects.html
{% extends "base.html" %}

{% block page %}

  <article class="projects">
    <h2>My projects from different events</h2>
    <ul>
      <a href="https://github.com/banditi/geography-lesson">Torrent Analytics (MIPT Hackathon 2014 May)</a>
      <li><a href="https://github.com/banditi/geography-lesson">Geography Lesson (MIPT Hackathon 2014 October)</a></li>
      <li><a href="https://rawgit.com/banditi/real-time-app/master/index.html">Real Time App (MIPT Hackathon 2014 November)</a>, also available on <a href="https://github.com/banditi/real-time-app">GitHub</a></li>
      <li><a href="http://master-igor.com/findme/">FindMe (MIPT Hackathon 2015 February)</a></li>
    </ul>
  </article>

{% endblock page %}

main/templates/scrobbler.html
{% extends "base.html" %}
{% load staticfiles %}

{% block end_script %}
  <link rel="stylesheet" href="{% static "css/scrobbler.css" %}">
  <script src="{% static "js/scrobbler.js" %}"></script>
{% endblock end_script %}


{% block page %}

  <article class="scrobbler_form">
    <form id="change_name" class="col-md-8">
      <div class="input-group input-group-lg">
        <input id="new_nick" type="text" class="form-control" placeholder="Enter nick from Last.fm">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">Go!</button>
        </span>
      </div>
    </form>
  </article>

  <article class="scrobbler">
    <h2>Now playing</h2>
    <table class="table table-hover table-bordered">
      <col width="20%">
      <tr>
        <td class="text-right"><span id="label_nick"><strong>User</strong></span></td>
        <td><span id="nick">{{ track.nick }}</span></td>
      </tr>
      <tr>
        <td class="text-right"><span id="label_name"><strong>Track</strong></span></td>
        <td><a href="{{ track.url }}" id="name" target="_blank">{{ track.name }}</a></td>
      </tr>
      <tr>
        <td class="text-right"><span id="label_artist"><strong>Artist</strong></span></td>
        <td><span id="artist">{{ track.artist }}</span></td>
      </tr>
    </table>
    <div>
      <img src="http://screenshots.en.sftcdn.net/blog/en/2012/10/10-15-2012-2-22-52-PM-300x300.png" alt="Image" id="img" class="img-circle">
    </div>
  </article>

{% endblock page %}

main/templates/travel.html
{% extends "base.html" %}

{% block page %}
<article class="travel">
  <iframe src="https://www.google.com/maps/d/u/0/embed?mid=zPBxiJKvo5dA.kzKkFLyF0abI" width="100%" height="480"></iframe>
</article>
{% endblock page %}